CREATE TABLE GRUPA(
	ID integer NOT NULL,
	NAZWA varchar(10) NOT NULL,
	CONSTRAINT GRUPA_PK PRIMARY KEY (ID)
);

CREATE TABLE KLUB(
	ID integer NOT NULL,
	NAZWA varchar(100) NOT NULL,
	CONSTRAINT KLUB_PK PRIMARY KEY (ID)
);
