
ALTER TABLE SYTUACJA
ALTER COLUMN nazwa TYPE varchar(40);

DROP TABLE ZAWODNICY;
CREATE TABLE ZAWODNIK(
	ID integer NOT NULL,
	pozycja_ID integer NULL,
	team_ID integer NULL,
	klub_ID integer NULL,
	nazwa varchar(50) NULL,
	data_urodzenia date NULL,
	wzrost integer NULL,
	CONSTRAINT ZAWODNIK_PK PRIMARY KEY (ID),
	CONSTRAINT ZAWODNIK_FK_POZYCJA FOREIGN KEY (pozycja_ID) REFERENCES POZYCJA (ID),
	CONSTRAINT ZAWODNIK_FK_TEAM FOREIGN KEY (team_ID) REFERENCES TEAM (ID),
	CONSTRAINT ZAWODNIK_FK_KLUB FOREIGN KEY (klub_ID) REFERENCES KLUB (ID)
);