CREATE TABLE GRUPA(
	ID integer NOT NULL,
	NAZWA varchar(10) NOT NULL,
	CONSTRAINT GRUPA_PK PRIMARY KEY (ID)
);

CREATE TABLE KLUB(
	ID integer NOT NULL,
	NAZWA varchar(100) NOT NULL,
	CONSTRAINT KLUB_PK PRIMARY KEY (ID)
);

CREATE TABLE KRAJ(
	ID integer NOT NULL,
	nazwa varchar(30) NULL,
	CONSTRAINT KRAJ_PK PRIMARY KEY (ID)
);

CREATE TABLE STADION(
	ID integer NOT NULL,
	nazwa varchar(40) NOT NULL,
	pojemnosc integer NOT NULL,
	miasto varchar(50) NOT NULL,
	CONSTRAINT STADION_PK PRIMARY KEY (ID)
);
	
CREATE TABLE POZYCJA(
	ID integer NOT NULL,
	nazwa varchar(25) NOT NULL,
	CONSTRAINT POZYCJA_PK PRIMARY KEY (ID)
);

CREATE TABLE REZULTAT(
	ID integer NOT NULL,
	nazwa varchar(20) NULL,
	CONSTRAINT REZULTAT_PK PRIMARY KEY (ID)
);

CREATE TABLE STREFA(
	ID integer NOT NULL,
	nazwa varchar(80) NOT NULL,
	strefa_kod varchar(10) NOT NULL,
	CONSTRAINT STREFA_PK PRIMARY KEY (ID)
);

CREATE TABLE SYTUACJA(
	ID integer NOT NULL,
	nazwa varchar(40) NULL,
	CONSTRAINT SYTUACJA_PK PRIMARY KEY (ID)
);

CREATE TABLE TRENER(
	ID integer NOT NULL,
	nazwa varchar(50) NULL,
	kraj_ID integer not NULL,
	CONSTRAINT TRENER_PK PRIMARY KEY (ID),
	CONSTRAINT TRENER_FK_KRAJ FOREIGN KEY (kraj_ID) REFERENCES KRAJ (ID)
);

CREATE TABLE SEDZIA(
	ID integer NOT NULL,
	nazwa varchar(50) NOT NULL,
	kraj_ID integer NOT NULL,
	strefa_ID integer NOT NULL,
	CONSTRAINT SEDZIA_PK PRIMARY KEY (ID),
	CONSTRAINT SEDZIA_FK_KRAJ FOREIGN KEY (kraj_ID) REFERENCES KRAJ (ID),
	CONSTRAINT SEDZIA_FK_STREFA FOREIGN KEY (strefa_ID) REFERENCES STREFA (ID)
);

CREATE TABLE TEAM(
	ID integer NOT NULL,
	nazwa varchar(50) NOT NULL,
	grupa_ID integer NULL,
	strefa_ID integer NULL,
	trener_ID integer NOT NULL,
	CONSTRAINT TEAM_PK PRIMARY KEY (ID),
	CONSTRAINT TEAM_FK_GRUPA FOREIGN KEY (grupa_ID) REFERENCES GRUPA (ID),
	CONSTRAINT TEAM_FK_TRENER FOREIGN KEY (trener_ID) REFERENCES TRENER (ID)
);

CREATE TABLE ZAWODNIK(
	ID integer NOT NULL,
	pozycja_ID integer NULL,
	team_ID integer NULL,
	klub_ID integer NULL,
	nazwa varchar(50) NULL,
	data_urodzenia date NULL,
	wzrost integer NULL,
	CONSTRAINT ZAWODNIK_PK PRIMARY KEY (ID),
	CONSTRAINT ZAWODNIK_FK_POZYCJA FOREIGN KEY (pozycja_ID) REFERENCES POZYCJA (ID),
	CONSTRAINT ZAWODNIK_FK_TEAM FOREIGN KEY (team_ID) REFERENCES TEAM (ID),
	CONSTRAINT ZAWODNIK_FK_KLUB FOREIGN KEY (klub_ID) REFERENCES KLUB (ID)
);

