#spring:
#  profiles:
#    active: @spring.profiles.active@


#security:
#  ignored: /**

logging:
  file:
    name: my.log
spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true
  output:
    ansi:
      enabled: ALWAYS
  security:
    user:
      name: user
      password: user
  jpa:
    open-in-view: false
server:
  port : 8181
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: sekret
    pool-size: 30