#spring:
#  profiles:
#    active: @spring.profiles.active@


spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: sekret
    pool-size: 30
server:
  port : 8181
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: sekret
    pool-size: 30

